import type { NextPage } from 'next'
import Head from 'next/head'
import NavigationBar from '../components/NavigationBar'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>HooBank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hoobank.svg" />
      </Head>
      <NavigationBar />
    </div>
  )
}

export default Home
